---
title: "caRtographysandbox"
output: html_document
---
# Setup
``` {r libraries and API echo=FALSE}
library(geofacet)
library(rnaturalearth)
library(maps)
library(ggmap)
library(sf)
library(ggrepel)
library(ggtext)
library(gganimate)
library(tidyverse)
# register_stadiamaps("YOUR-API-KEY", write = FALSE)
```
``` {r set defaults echo=FALSE}
# set default theme for ggplot2
ggplot2::theme_set(ggplot2::theme_void(base_size = 16))
# set default figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 8, fig.asp = 0.618,
  fig.retina = 2, dpi = 150
)
```

# Map
``` {r importing fire boundaries}
# importing shape files
fire_shp <- st_read("data/firebnds/US_HIST_FIRE_PERIMTRS_2000_2018_DD83.shp")
fire_shp
```
``` {r importing states}
state_shp <- st_read("data/statemap/cb_2018_us_state_20m.shp")
# change projection to match fire perimeter data
state_reproj <- st_transform(state_shp, "WGS84")
```
``` {r importing coastline}
coast_shp <- st_read("data/ne_50m_coastline/ne_50m_coastline.shp")
# change projection to match fire perimeter data
coast_reproj <- st_transform(coast_shp, "WGS84")
```
``` {r RUN THIS}
# filtering by year
fire_shp2000 <- fire_shp %>%
  filter(fireyear == "2000")
# making the map
fire_map <- ggplot() +
  geom_sf(data = coast_reproj, color = "#CCA77B", linewidth = 0.2) +
  geom_sf(data = state_reproj, fill = "#E2CFB6") +
  geom_sf(data = fire_shp2000, color = "#f59929", fill = "#f59929") +
  coord_sf(xlim = c(-173,-64), ylim = c(15,72)) +
  labs(title = "Fire Boundaries in the US, 2000-2018") +
  annotate(geom = "text",
           x = -170, y = 16.5,
           label = "2000",
           color = "#76562E", size = 6,
           family = "serif", fontface = "bold") +
  theme(
    plot.background = element_rect(color = "black", fill = "#F9F5F0"),
    plot.title = element_text(color = "#76562E", face = "bold", family = "serif", hjust = 0.5)
  )
fire_map
# saving the map
ggsave("images/fire_map2000.png", fire_map)
```