# Who is Andrea Conover?
Hi! I'm Andrea, a mixed methods social scientist with six years of professional experience writing, teaching, and project managing. My research interests revolve around human-environment interactions, particularly perceptions of wildland-urban interfaces and urban sprawl. I'm currently an MA candidate at the University of Chicago through their Master's Program in the Social Sciences, currently on track for degree completion in early June, 2025. My thesis, "Competing Discourses in News Coverage of the 2024 Bridge Fire", examines conflicts of sensationalism vs. rationalism and human dominance vs. untameable nature in the coverage of southern California wildfires.

See ["About"](https://andreaconover.github.io/about.html) for more details of my teaching and work experience!


# Projects
This website includes a portfolio of projects I completed during my MA program, many of which are broadly related to climate change or environmental issues.

Looking for animated data visualizations? Check out my ["Plotly"](https://andreaconover.github.io/plotly.html) project.

Interested in seeing a web app exploring climate change communications topics? Take a look at ["Shiny"](https://andreaconover.github.io/shiny.html).

Looking for interactive data dashboards? Check out my work in ["Tableau"](https://andreaconover.github.io/tableau.html).

Finally, check out my [Cartography](https://andreaconover.github.io/cartography.html) projects for maps created using R and QGIS.