---
title: "plotlysandbox"
output: html_document
---

``` {r echo=FALSE}
# libraries
library(htmlwidgets)
library(ggrepel)
library(ggtext)
library(plotly)
library(gganimate)
library(tidyverse)
# set default theme for ggplot2
ggplot2::theme_set(ggplot2::theme_light(base_size = 8))
# set default figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 8, fig.asp = 0.618,
  fig.retina = 2, dpi = 150
)
# importing data
cc_fema <- read.csv("data/ypccc/harm_fema10-23.csv")
```
``` {r plot}
# Plotly
harm_fema_plot <- ggplot(cc_fema, aes(y = fema, x = harmus)) +
  geom_point(aes(color = harmus, frame = year,
                 text = paste("FEMA: $", scales::label_comma(scale = 0.001)(fema), "<br>Belief in Harm to US: ", harmus, "%<br>State: ", geoname))) +
  scale_y_continuous(name = "FEMA Public Assistance Funded Projects Total per State",
    breaks = seq(from = 0, to = 3500000000, by = 500000000),
    labels = c("$0", "$500M", "$1B", "$1.5B", "$2B", "$2.5B", "$3B", "$3.5B")) +
  scale_x_continuous(name = "% who believe global warming will harm people in the US",
    breaks = seq(from = 35, to = 75, by = 5),
    labels = c("35%", "40%", "45%", "50%", "55%", "60%", "65%", "70%", "75%")) +
  scale_color_viridis_c(option = "B", guide = "none", begin = 0.2, end = 0.9) +
  theme_minimal()
harm_fema_plot
```
``` {r converting to plotly}
# converting to plotly
harm_fema_plotly <- ggplotly(harm_fema_plot, tooltip = "text")
harm_fema_plotly <- harm_fema_plotly %>%
  animation_opts(1000, easing = "cubic-out")
harm_fema_plotly
```
``` {r saving the widget}
htmlwidgets::saveWidget(as_widget(harm_fema_plotly), "images/harm_fema_plotly.html")
```

``` {r}
# libraries
library(plotly)
library(tidyverse)
## set default theme for ggplot2
ggplot2::theme_set(ggplot2::theme_light(base_size = 8))
# set default figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 8, fig.asp = 0.618,
  fig.retina = 2, dpi = 150
)
# importing data
data_allvars <- read.csv("data/ypccc/YPCCCRegionalizedVariables.csv")
# tidying
data_harmus <- data_allvars %>%
  filter(variable == "harmus") %>%
  gather("X2010", "X2011", "X2012", "X2013", "X2014", "X2015", "X2016", "X2017", "X2018", "X2019", "X2020", "X2021", "X2022", "X2023", key = "year", value = "harmus")
data_harmus$year <- gsub("X", "", data_harmus$year) %>%
  as.numeric()
# adding yearly mean column
data_harmus <- data_harmus %>%
  group_by(year) %>%
  mutate(mean_year = mean(harmus))
```
``` {r}
# plotting the plot
harm_plot <- ggplot(data_harmus, aes(x = year, y = harmus)) +
    geom_boxplot(aes(group = year, fill = mean_year)) +
    scale_y_continuous(
      breaks = seq(from = 0, to = 100, by = 10),
      labels = scales::label_percent(scale = 1)) +
    labs(
      x = "Year",
      y = "% who believe global warming will harm people in the US"
    ) +
    scale_fill_viridis_c(option = "B", guide = "none", begin = 0.2, end = 0.9) +
    theme_minimal()
harm_plot
```
``` {r}
# plotly plot
harm_plotly <- ggplotly(harm_plot)
harm_plotly
```

``` {r}
htmlwidgets::saveWidget(as_widget(harm_plotly), "images/harm_plotly.html")
```