These are the files for my website. The website and accompanying files were submitted for credit as my final project of MACS 40700 Data Visualization course while completing the Master's Program in the Social Sciences at the University of Chicago.

# Design Considerations

## Website
In putting together the website, I initially envisioned and drafted the website as being organized based on each skill I wanted to highlight. However, based on early feedback, I decided to reorganize the website based on each substantive project area instead.

I decided to use the “readable” GitHub theme for three reasons: it looked clean and minimalistic, it should be relatively accessible given its high contrast between background and text, and blue is my favorite color.

## Research Topics
My goal in designing this website was to create a portfolio-like showcase of my data visualization and technical skills, and I wanted to do so while exploring topics of particular interest. Given that my thesis examines competing discourses in news coverage of California wildfires, I decided to tackle two related topics: climate change communications and wildfire in recent history.

### Climate Change Communications
When exploring climate change communications as a broad topic, I wondered if a higher prevalence of natural disasters (or more catastrophic natural disasters) correlated with places where people are more likely to believe that climate change could cause them direct harm. I decided to examine this in several dimensions:
1.	Do states that see higher damage from natural disasters (as seen through FEMA Public Assistance Funded Projects) have a higher percentage of people who believe that global warming will harm people in the United States?
a.	Is the prevalence of this belief regional to begin with?
b.	Has belief in the harmful effects of climate change increased over time?
2.	Do different regions hear about climate change in the media with the same frequency?
3.	Is there a relationship between states where large percentages of people believe global warming is happening and states where large percentages of people believe most scientists think global warming is happening?

#### Methods

First, I knew that I wanted to group several of these questions and enable viewers to interact within the context of climate change communications, so I decided to make a multi-visualization Shiny app. See the “Design Considerations” tab in the app at https://aconover.shinyapps.io/assignment-5-AndreaConover/ for further details about generating the plots there. However, when embedding the app into the website, I also took the opportunity to integrate some feedback and make some small improvements. I enabled viewers to select multiple states in the plot examining what percent of people in each state believe that global warming will harm people in the US. I also added a little more color to the plot examining what percent of people in each region hear about global warming in the media at least weekly. Finally, I improved the formatting of the text elements of the app by including additional headers and bolding.

However, the app didn’t address one of the research questions that I considered early in my research process: Do states that see higher damage from natural disasters (as seen through FEMA Public Assistance Funded Projects) have a higher percentage of people who believe that global warming will harm people in the United States? To examine this question, I decided that Plotly was the best tool because of its capacity for animation and interaction. I knew that I wanted to examine the potential relationship on a state-by-state level, which would include many data points. The best way to make those data points meaningful to a viewer would be to allow them to interact with them for more detail. I also wanted to examine the potential relationship over time, which animation would be useful for.

Early drafts of the plot had several issues: the outlier that was Hurricane Sandy relief in New York in 2012 (roughly $10 billion more than the next highest amount of aid), unsuitable transitioning between the data points, poor formatting of the tooltip when mousing over the data points, and thick clustering of the data along the Y-axis (partially due to the outlier and partially due to the assignment of the belief variable to Y and the FEMA funding to X). The extremity of the outlier led me to eventually decide to exclude it with clear explanation of what was excluded and why beneath the graph. The default transitions between states in the animation was unsuitable because the data points spent as much time traveling as they did at rest; it was difficult to visually process the location of each of the points per year before the transition to the next year began. I resolved this with some experimentation and eventually settled on a transition where each point travelled quickly toward its next position, then slowed to a stop, which allows viewers more time to see how the data is settling before the next transition begins. The tooltip formatting required extensive troubleshooting but was well worth the time given how much it added to the plot when complete. The data clustering was resolved by swapping axes: what had been clustering along the Y now became clustering along the X, which was significantly less disruptive visually. I also decided to double-encode the belief variable on the X-axis as well as a color scale because, in addition to being more aesthetically pleasing, it allows viewers to see the general trend of movement toward the right of the graph over time.

The visual observation of this trend inspired my final visualization on this topic. In order to examine the change in the belief that global warming will harm people in the United States over time, I decided on a series of box plots with the data grouped by year. Similarly to the previous visualization, I wanted to increase its visual appeal by including color. An early draft of the visualization had the box plots colored by year to visually distinguish them from one another; however, the number of box plots meant that the colors weren’t helpful but rather confusing. Instead, I decided to color-code the boxes according to the mean value of each year to visually reinforce the trend.

#### Discussion

Between the app and the Plotly plots, viewers can come away from these visualizations with several conclusions about climate change communications. First, beliefs about climate change (including about its potential harms, the frequency it appears in the media, and whether scientists are in consensus on the topic) are noticeably regional. Second, belief that climate change could harm people in the United States is generally on the rise. Finally, FEMA funding is unrelated to the prevalence of the belief that global warming could be harmful to Americans. This particular finding is likely influenced by the many political and economic considerations that contribute to FEMA funding decisions.

### Wildfire in Recent History

When exploring wildfire in recent history, I became curious about ways in which the fire return interval could be visualized. Fire return interval (FRI) is the number of years between fires in an area and is highly dependent on the type of wilderness in the area. It seemed that an animated map showing fire boundaries from each year over the course of several decades might have the potential to visually demonstrate which areas experienced the shortest FRI and most frequent fire, as well as giving me the opportunity to extend my skills from my previous Cartographic Design and Geovisualization class.

#### Methods

First, I found the necessary (and publicly available) shape files for fire boundaries; however, the fire boundaries needed a background, so I also found some basic shape files of the United States to put behind the fire boundaries after a quick reprojection into the WGS 84 projection used by the fire boundaries file. The fire boundaries shape files were prohibitively large, so I knew that I would need to generate an image file that I could display rather than having the website try to render the map every time it was loaded. As I continued drafting, I knew that I wanted to choose thematically appropriate colors while avoiding playing into the kind of sensationalism that is very common when discussing fire. As a result, I decided on orange for the fire boundaries but kept the background and text in a palette of neutral browns. I also found that, if I were to include Alaska and Hawaii (and given Alaska’s frequent wildfires, I definitely wanted to include Alaska), I needed some other way of filling the space around the lower 48. I decided to use Natural Earth’s publicly available coastal shape files (the 10m were far too detailed and the 110m too general, but the 50m had an appropriate level of intricacy when compared to the rest of the map) with a light brown color to give the general impression of the remaining landmass in the space without detracting from the main elements of the map. The rendering time for animating the map was prohibitive, so I decided to run the dataset through a filter per year and then splice the resulting yearly PNGs together into a GIF instead.

#### Discussion

With this animated map, viewers can watch as the yearly wildfires trace across the map and see that some years had larger areas dealing with wildfires while other years had smaller ignited areas. Viewers can also get the impression of which regions have shorter fire return intervals and which areas have longer ones as the fire boundaries are redrawn each year.
