---
title: "Tableau"
output: html_document
---

## 2023 Baby Names
I developed this Tableau dashboard to enable users to explore the Social Security Administration's public data about baby names from 2023. I emphasized visual appeal through a fun, non-traditional color scheme and a variety of visualization types that each expressed a unique aspect of the dataset.
<iframe src="https://public.tableau.com/views/BabyNamesof2023/BabyNamesDashboard?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link:showVizHome=no&:embed=true" width="1005px" height="845px"></iframe>

## Los Angeles Airbnb Listings
This Tableau dashboard enables users to explore data from Inside Airbnb about listings in Los Angeles in 2024. Because of the highly spatial nature of the data, I centered an interactive map in the dashboard and linked all other interactive elements to it. I also kept a much simpler color scheme in favor of communicating information through size and location instead. This was particularly helpful given the skewed distribution of the data, which meant that traditional color scales were rather uninformative.
<iframe src="https://public.tableau.com/views/AirBnBLocationsinLosAngeles/Dashboard1?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link:showVizHome=no&:embed=true" width="1005px" height="845px"></iframe>